name: CI - Linting, Formatting, Testing

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint:fix

      - name: Run Prettier Fix (Auto-format code)
        run: npm run format

      - name: Check formatting after fix
        run: npm run format:check

      - name: Run NPM Audit
        run: npm run audit

      - name: Run Tests with Coverage
        run: npm run test -- --passWithNoTests

      - name: Upload Code Coverage Summary to GitHub
        if: always()
        run: |
          echo "### Code Coverage Summary" >> $GITHUB_STEP_SUMMARY
          if [ -f coverage/coverage-summary.json ]; then
            cat coverage/coverage-summary.json >> $GITHUB_STEP_SUMMARY
          else
            echo "No coverage summary found." >> $GITHUB_STEP_SUMMARY
          fi

      - name: Auto-merge main -> production
        if: success() && github.ref == 'refs/heads/main'
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git clone --single-branch --branch production https://x-access-token:${GH_PAT}@github.com/${{ github.repository }} repo
          cd repo
          git remote add upstream https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}
          git fetch upstream main
          git merge upstream/main --no-edit
          git push origin production
